import PDEIdeas.BoxCoordinateRellich

/-!
# Reduction of box compactness to one scalar Rellich map

The scalar coordinate graph closure is generated by one velocity component
and the corresponding row of the full gradient. Every coordinate of the full
vector-valued Rellich map factors through the same scalar first-coordinate
projection. Compactness of this one scalar map therefore implies compactness
of both the full and divergence-free box embeddings.
-/

open MeasureTheory Real InnerProductSpace Set
open scoped ENNReal NNReal RealInnerProductSpace

noncomputable section

local instance : Fact (1 ≤ (2 : ℝ≥0∞)) := ⟨by norm_num⟩

variable {n : ℕ}

/-- Scalar gradient values, represented as Euclidean vectors. -/
abbrev BoxScalarGradientValue (n : ℕ) := BoxVelocityValue n

/-- Scalar-gradient L2 space on the box. -/
abbrev BoxScalarGradientL2
    (I : BoxIntegral.Box (Fin (n + 1))) :=
  BoxVelocityL2 I

/-- Product L2 space carrying a scalar field and its full gradient. -/
abbrev BoxScalarEnergyAmbient
    (I : BoxIntegral.Box (Fin (n + 1))) :=
  WithLp 2 (BoxScalarL2 I × BoxScalarGradientL2 I)

/-- Extract one row from a Euclidean derivative matrix. -/
def boxGradientRowValue
    (i : Fin (n + 1)) :
    BoxGradientValue n →L[ℝ] BoxScalarGradientValue n :=
  (EuclideanSpace.equiv (Fin (n + 1)) ℝ).symm.toContinuousLinearMap.comp
    ((Pi.compRightL ℝ
      (fun _ : Fin (n + 1) × Fin (n + 1) => ℝ)
      (fun j => (i, j))).comp
        (EuclideanSpace.equiv
          (Fin (n + 1) × Fin (n + 1)) ℝ).toContinuousLinearMap)

@[simp]
theorem boxGradientRowValue_apply
    (i j : Fin (n + 1))
    (A : BoxGradientValue n) :
    boxGradientRowValue i A j = A (i, j) := by
  rfl

/-- Extract one gradient row from a matrix-valued L2 field. -/
def boxGradientRowLp
    (I : BoxIntegral.Box (Fin (n + 1)))
    (i : Fin (n + 1)) :
    BoxGradientL2 I →L[ℝ] BoxScalarGradientL2 I :=
  (boxGradientRowValue i).compLpL 2 (BoxMeasure I)

/-- Extract one scalar velocity component and its gradient row from the full
vector graph ambient space. -/
def boxFullAmbientToScalarCoordinate
    (I : BoxIntegral.Box (Fin (n + 1)))
    (i : Fin (n + 1)) :
    BoxEnergyAmbient I →L[ℝ] BoxScalarEnergyAmbient I :=
  let e := WithLp.prodContinuousLinearEquiv
    2 ℝ (BoxScalarL2 I) (BoxScalarGradientL2 I)
  (e.symm :
      (BoxScalarL2 I × BoxScalarGradientL2 I) →L[ℝ]
        BoxScalarEnergyAmbient I) ∘L
    (((boxVelocityCoordinateLp I i).comp
        (boxEnergyVelocityProjection I)).prod
      ((boxGradientRowLp I i).comp
        (boxEnergyGradientProjection I)))

@[simp]
theorem boxFullAmbientToScalarCoordinate_velocity
    (I : BoxIntegral.Box (Fin (n + 1)))
    (i : Fin (n + 1))
    (z : BoxEnergyAmbient I) :
    WithLp.fstL 2 ℝ (BoxScalarL2 I) (BoxScalarGradientL2 I)
        (boxFullAmbientToScalarCoordinate I i z) =
      boxVelocityCoordinateLp I i
        (boxEnergyVelocityProjection I z) := by
  rfl

@[simp]
theorem boxFullAmbientToScalarCoordinate_gradient
    (I : BoxIntegral.Box (Fin (n + 1)))
    (i : Fin (n + 1))
    (z : BoxEnergyAmbient I) :
    WithLp.sndL 2 ℝ (BoxScalarL2 I) (BoxScalarGradientL2 I)
        (boxFullAmbientToScalarCoordinate I i z) =
      boxGradientRowLp I i
        (boxEnergyGradientProjection I z) := by
  rfl

/-- Scalar coordinate graph points obtained from smooth zero-face vector
fields. -/
def smoothBoxScalarCoordinateGraphSet
    (I : BoxIntegral.Box (Fin (n + 1))) :
    Set (BoxScalarEnergyAmbient I) :=
  {z | ∃ (i : Fin (n + 1)) (u : SmoothBoxH1ZeroField I),
    z = boxFullAmbientToScalarCoordinate I i u.graphPoint}

/-- Linear span of the smooth scalar coordinate graph points. -/
def smoothBoxScalarCoordinateGraphCore
    (I : BoxIntegral.Box (Fin (n + 1))) :
    Submodule ℝ (BoxScalarEnergyAmbient I) :=
  Submodule.span ℝ (smoothBoxScalarCoordinateGraphSet I)

/-- Scalar zero-face coordinate graph closure. -/
abbrev BoxH1ZeroScalarCoordinate
    (I : BoxIntegral.Box (Fin (n + 1))) :=
  (smoothBoxScalarCoordinateGraphCore I).topologicalClosure

/-- First-coordinate projection on the scalar graph ambient space. -/
def boxScalarEnergyVelocityProjection
    (I : BoxIntegral.Box (Fin (n + 1))) :
    BoxScalarEnergyAmbient I →L[ℝ] BoxScalarL2 I :=
  WithLp.fstL 2 ℝ (BoxScalarL2 I) (BoxScalarGradientL2 I)

/-- The single scalar Rellich map needed for all vector components. -/
def boxScalarCoordinateEnergyToVelocity
    (I : BoxIntegral.Box (Fin (n + 1))) :
    BoxH1ZeroScalarCoordinate I →L[ℝ] BoxScalarL2 I :=
  (boxScalarEnergyVelocityProjection I).comp
    (smoothBoxScalarCoordinateGraphCore I).topologicalClosure.subtypeL

theorem boxFullGraphCore_map_scalarCoordinate_le
    (I : BoxIntegral.Box (Fin (n + 1)))
    (i : Fin (n + 1)) :
    (smoothBoxH1ZeroGraphCore I).map
        (boxFullAmbientToScalarCoordinate I i).toLinearMap ≤
      smoothBoxScalarCoordinateGraphCore I := by
  rw [smoothBoxH1ZeroGraphCore,
    smoothBoxScalarCoordinateGraphCore]
  apply (Submodule.map_span_le
    (boxFullAmbientToScalarCoordinate I i).toLinearMap
    (smoothBoxH1ZeroGraphSet I)
    (Submodule.span ℝ
      (smoothBoxScalarCoordinateGraphSet I))).2
  rintro _ ⟨u, rfl⟩
  exact Submodule.subset_span ⟨i, u, rfl⟩

/-- Map a full vector graph state to the scalar graph state formed by one
component and its gradient row. -/
def boxFullEnergyToScalarCoordinate
    (I : BoxIntegral.Box (Fin (n + 1)))
    (i : Fin (n + 1)) :
    BoxH1ZeroFull I →L[ℝ] BoxH1ZeroScalarCoordinate I :=
  ((boxFullAmbientToScalarCoordinate I i).comp
      (smoothBoxH1ZeroGraphCore I).topologicalClosure.subtypeL).codRestrict
    (smoothBoxScalarCoordinateGraphCore I).topologicalClosure fun u => by
      have huMap :
          boxFullAmbientToScalarCoordinate I i
              (u : BoxEnergyAmbient I) ∈
            (smoothBoxH1ZeroGraphCore I).topologicalClosure.map
              (boxFullAmbientToScalarCoordinate I i).toLinearMap :=
        ⟨u, u.property, rfl⟩
      have huClosure :
          boxFullAmbientToScalarCoordinate I i
              (u : BoxEnergyAmbient I) ∈
            ((smoothBoxH1ZeroGraphCore I).map
              (boxFullAmbientToScalarCoordinate I i).toLinearMap
            ).topologicalClosure :=
        (smoothBoxH1ZeroGraphCore I).topologicalClosure_map
          (boxFullAmbientToScalarCoordinate I i) huMap
      exact Submodule.topologicalClosure_mono
        (boxFullGraphCore_map_scalarCoordinate_le I i) huClosure

@[simp]
theorem boxScalarCoordinateEnergyToVelocity_fullEnergy
    (I : BoxIntegral.Box (Fin (n + 1)))
    (i : Fin (n + 1))
    (u : BoxH1ZeroFull I) :
    boxScalarCoordinateEnergyToVelocity I
        (boxFullEnergyToScalarCoordinate I i u) =
      boxFullEnergyToVelocityCoordinate I i u := by
  rfl

/-- Compactness of the single scalar graph projection implies compactness of
the full vector graph projection. -/
theorem boxFullEnergyToVelocity_isCompactOperator_of_scalarRellich
    (I : BoxIntegral.Box (Fin (n + 1)))
    (hRellich :
      IsCompactOperator (boxScalarCoordinateEnergyToVelocity I)) :
    IsCompactOperator (boxFullEnergyToVelocity I) := by
  apply (boxFullEnergyToVelocity_isCompactOperator_iff_coordinates I).2
  intro i
  have hcomp := hRellich.comp_clm
    (boxFullEnergyToScalarCoordinate I i)
  simpa only [Function.comp_apply,
    boxScalarCoordinateEnergyToVelocity_fullEnergy] using hcomp

/-- The ordinary scalar zero-trace Rellich theorem implies compactness of the
divergence-free canonical box map. -/
theorem boxEnergyToState_isCompactOperator_of_scalarRellich
    (I : BoxIntegral.Box (Fin (n + 1)))
    (hRellich :
      IsCompactOperator (boxScalarCoordinateEnergyToVelocity I)) :
    IsCompactOperator (boxEnergyToState I) :=
  boxEnergyToState_isCompactOperator_of_fullRellich I
    (boxFullEnergyToVelocity_isCompactOperator_of_scalarRellich I hRellich)

/-- Coordinate realization of the full scalar gradient. -/
def boxScalarGradientValue
    (u' : (Fin (n + 1) → ℝ) →
      (Fin (n + 1) → ℝ) →L[ℝ] ℝ)
    (x : Fin (n + 1) → ℝ) :
    BoxScalarGradientValue n :=
  WithLp.toLp 2 fun j => u' x (Pi.single j 1)

/-- Smooth scalar zero-face fields with square-integrable value and full
gradient. -/
structure SmoothBoxScalarH1ZeroField
    (I : BoxIntegral.Box (Fin (n + 1))) where
  field : (Fin (n + 1) → ℝ) → ℝ
  derivative :
    (Fin (n + 1) → ℝ) →
      (Fin (n + 1) → ℝ) →L[ℝ] ℝ
  hasFDerivAt_field :
    ∀ x ∈ interior (BoxIntegral.Box.Icc I),
      HasFDerivAt field (derivative x) x
  continuousOn_field :
    ContinuousOn field (BoxIntegral.Box.Icc I)
  zeroDirichlet_field :
    ZeroDirichletScalarOnBox I field
  field_memLp :
    MemLp field 2 (BoxMeasure I)
  gradient_memLp :
    MemLp (boxScalarGradientValue derivative) 2 (BoxMeasure I)

namespace SmoothBoxScalarH1ZeroField

def velocityLp
    {I : BoxIntegral.Box (Fin (n + 1))}
    (u : SmoothBoxScalarH1ZeroField I) :
    BoxScalarL2 I :=
  u.field_memLp.toLp u.field

def gradientLp
    {I : BoxIntegral.Box (Fin (n + 1))}
    (u : SmoothBoxScalarH1ZeroField I) :
    BoxScalarGradientL2 I :=
  u.gradient_memLp.toLp (boxScalarGradientValue u.derivative)

def graphPoint
    {I : BoxIntegral.Box (Fin (n + 1))}
    (u : SmoothBoxScalarH1ZeroField I) :
    BoxScalarEnergyAmbient I :=
  WithLp.toLp 2 (u.velocityLp, u.gradientLp)

end SmoothBoxScalarH1ZeroField

/-- One scalar component of a smooth zero-face vector field, with the
corresponding derivative row. -/
def SmoothBoxH1ZeroField.scalarComponent
    {I : BoxIntegral.Box (Fin (n + 1))}
    (u : SmoothBoxH1ZeroField I)
    (i : Fin (n + 1)) :
    SmoothBoxScalarH1ZeroField I where
  field := fun x => u.field x i
  derivative := fun x =>
    (ContinuousLinearMap.proj i :
      (Fin (n + 1) → ℝ) →L[ℝ] ℝ).comp (u.derivative x)
  hasFDerivAt_field := by
    intro x hx
    exact (ContinuousLinearMap.proj i :
      (Fin (n + 1) → ℝ) →L[ℝ] ℝ).hasFDerivAt.comp x
      (u.hasFDerivAt_field x hx)
  continuousOn_field :=
    (ContinuousLinearMap.proj i :
      (Fin (n + 1) → ℝ) →L[ℝ] ℝ).continuous.comp_continuousOn
      u.continuousOn_field
  zeroDirichlet_field :=
    ZeroDirichletVectorOnBox.component I u.field
      u.zeroDirichlet_field i
  field_memLp := by
    simpa [boxVelocityCoordinateValue, boxVelocityValue] using
      u.velocity_memLp.continuousLinearMap_comp
        (boxVelocityCoordinateValue i)
  gradient_memLp := by
    simpa [boxScalarGradientValue, boxGradientValue] using
      u.gradient_memLp.continuousLinearMap_comp
        (boxGradientRowValue i)

@[simp]
theorem SmoothBoxH1ZeroField.scalarComponent_velocityLp
    {I : BoxIntegral.Box (Fin (n + 1))}
    (u : SmoothBoxH1ZeroField I)
    (i : Fin (n + 1)) :
    (u.scalarComponent i).velocityLp =
      boxVelocityCoordinateLp I i u.velocityLp := by
  apply Lp.ext
  filter_upwards [
    (boxVelocityCoordinateValue i).coeFn_compLpL u.velocityLp,
    u.velocity_memLp.coeFn_toLp,
    (u.scalarComponent i).field_memLp.coeFn_toLp] with x hcomp hu hscalar
  simp only [SmoothBoxScalarH1ZeroField.velocityLp,
    boxVelocityCoordinateLp]
  rw [hcomp, hscalar]
  simpa [SmoothBoxH1ZeroField.velocityLp, boxVelocityCoordinateValue,
    boxVelocityValue] using
      (congrArg (boxVelocityCoordinateValue i) hu).symm

@[simp]
theorem SmoothBoxH1ZeroField.scalarComponent_gradientLp
    {I : BoxIntegral.Box (Fin (n + 1))}
    (u : SmoothBoxH1ZeroField I)
    (i : Fin (n + 1)) :
    (u.scalarComponent i).gradientLp =
      boxGradientRowLp I i u.gradientLp := by
  apply Lp.ext
  filter_upwards [
    (boxGradientRowValue i).coeFn_compLpL u.gradientLp,
    u.gradient_memLp.coeFn_toLp,
    (u.scalarComponent i).gradient_memLp.coeFn_toLp] with x hcomp hu hscalar
  simp only [SmoothBoxScalarH1ZeroField.gradientLp,
    boxGradientRowLp]
  rw [hcomp, hscalar]
  simpa [SmoothBoxH1ZeroField.gradientLp,
    SmoothBoxScalarH1ZeroField.gradientLp,
    boxScalarGradientValue, boxGradientValue] using
      (congrArg (boxGradientRowValue i) hu).symm

@[simp]
theorem SmoothBoxH1ZeroField.scalarComponent_graphPoint
    {I : BoxIntegral.Box (Fin (n + 1))}
    (u : SmoothBoxH1ZeroField I)
    (i : Fin (n + 1)) :
    (u.scalarComponent i).graphPoint =
      boxFullAmbientToScalarCoordinate I i u.graphPoint := by
  change
    WithLp.toLp 2
      ((u.scalarComponent i).velocityLp,
        (u.scalarComponent i).gradientLp) =
    WithLp.toLp 2
      (boxVelocityCoordinateLp I i u.velocityLp,
        boxGradientRowLp I i u.gradientLp)
  rw [u.scalarComponent_velocityLp i,
    u.scalarComponent_gradientLp i]

/-- Graph points of arbitrary smooth scalar zero-face fields. -/
def smoothBoxScalarFullGraphSet
    (I : BoxIntegral.Box (Fin (n + 1))) :
    Set (BoxScalarEnergyAmbient I) :=
  Set.range SmoothBoxScalarH1ZeroField.graphPoint

/-- Linear span of the full smooth scalar graph. -/
def smoothBoxScalarFullGraphCore
    (I : BoxIntegral.Box (Fin (n + 1))) :
    Submodule ℝ (BoxScalarEnergyAmbient I) :=
  Submodule.span ℝ (smoothBoxScalarFullGraphSet I)

/-- Full scalar zero-trace H1 graph closure. -/
abbrev BoxH1ZeroScalarFull
    (I : BoxIntegral.Box (Fin (n + 1))) :=
  (smoothBoxScalarFullGraphCore I).topologicalClosure

/-- Velocity projection on the full scalar zero-trace graph closure. -/
def boxScalarFullEnergyToVelocity
    (I : BoxIntegral.Box (Fin (n + 1))) :
    BoxH1ZeroScalarFull I →L[ℝ] BoxScalarL2 I :=
  (boxScalarEnergyVelocityProjection I).comp
    (smoothBoxScalarFullGraphCore I).topologicalClosure.subtypeL

theorem smoothBoxScalarCoordinateGraphSet_subset_full
    (I : BoxIntegral.Box (Fin (n + 1))) :
    smoothBoxScalarCoordinateGraphSet I ⊆
      smoothBoxScalarFullGraphSet I := by
  rintro _ ⟨i, u, rfl⟩
  exact ⟨u.scalarComponent i,
    u.scalarComponent_graphPoint i⟩

theorem smoothBoxScalarCoordinateGraphCore_le_full
    (I : BoxIntegral.Box (Fin (n + 1))) :
    smoothBoxScalarCoordinateGraphCore I ≤
      smoothBoxScalarFullGraphCore I := by
  exact Submodule.span_mono
    (smoothBoxScalarCoordinateGraphSet_subset_full I)

/-- Inclusion of the scalar coordinate graph closure into the full scalar
zero-trace graph closure. -/
def boxScalarCoordinateToFull
    (I : BoxIntegral.Box (Fin (n + 1))) :
    BoxH1ZeroScalarCoordinate I →L[ℝ] BoxH1ZeroScalarFull I :=
  ((smoothBoxScalarCoordinateGraphCore I).topologicalClosure.subtypeL).codRestrict
    (smoothBoxScalarFullGraphCore I).topologicalClosure fun u =>
      Submodule.topologicalClosure_mono
        (smoothBoxScalarCoordinateGraphCore_le_full I) u.property

@[simp]
theorem boxScalarFullEnergyToVelocity_coordinate
    (I : BoxIntegral.Box (Fin (n + 1)))
    (u : BoxH1ZeroScalarCoordinate I) :
    boxScalarFullEnergyToVelocity I
        (boxScalarCoordinateToFull I u) =
      boxScalarCoordinateEnergyToVelocity I u := by
  rfl

/-- Full scalar Rellich compactness implies compactness of the scalar
coordinate graph projection. -/
theorem boxScalarCoordinateEnergyToVelocity_isCompactOperator_of_fullRellich
    (I : BoxIntegral.Box (Fin (n + 1)))
    (hRellich :
      IsCompactOperator (boxScalarFullEnergyToVelocity I)) :
    IsCompactOperator (boxScalarCoordinateEnergyToVelocity I) := by
  have hcomp := hRellich.comp_clm (boxScalarCoordinateToFull I)
  simpa only [Function.comp_apply,
    boxScalarFullEnergyToVelocity_coordinate] using hcomp

/-- The classical scalar zero-trace Rellich theorem implies compactness of
the divergence-free canonical box map. -/
theorem boxEnergyToState_isCompactOperator_of_scalarFullRellich
    (I : BoxIntegral.Box (Fin (n + 1)))
    (hRellich :
      IsCompactOperator (boxScalarFullEnergyToVelocity I)) :
    IsCompactOperator (boxEnergyToState I) :=
  boxEnergyToState_isCompactOperator_of_scalarRellich I
    (boxScalarCoordinateEnergyToVelocity_isCompactOperator_of_fullRellich
      I hRellich)

end
